server:
  port: 8082
palikka:
  jwt:
    keystore:
      signing:
        path: file:keystore-dev.p12
        pass: password
        type: pkcs12
      verification:
        path: file:truststore-dev.p12
        pass: password
        type: pkcs12
    token:
      user:
        issuer: palikka-dev-usr
        verification:
          key-alias: jwt-usr
      system:
        issuer: palikka-dev-sys
        signing:
          key-alias: jwt-sys
          key-pass: password
          validity-time: 10s
  integration:
    users-api:
      base-uri: http://palikka-users-api:8080
  game:
    file:
      name: server.jar
      path: /app # todo directory structure needs to exist currently, change?
      start-command: java -jar server.jar # todo omit name?
    process:
      stop-timeout: 10s
    status:
      host: 172.25.16.1
      port: 25565
# todo delete these - debugging only
logging:
  level:
    fi.jannetahkola.palikka: debug
    org.springframework.security: debug
    org.springframework.test.context.jdbc: debug # which sql scripts are executed
    org.springframework.jdbc.datasource.init: debug # which sql statements are executed