palikka:
  jwt:
    keystore-path: file:palikka.keystore  # read from filesystem
    keystore-pass: password
    keystore-type: pkcs12
    token:
      key-alias: jwt
      key-pass: password
      issuer: palikka-dev
      validity-time: 10s
  integration:
    users-api:
      base-uri: http://localhost:8080
  game:
    server:
      host: 172.25.16.1
      port: 25565
      file:
        name: server.jar
        path: /app # todo directory structure needs to exist currently, change?
        start-command: java -jar server.jar # todo omit name?
      stop-timeout-in-millis: 10000