server:
  servlet:
    context-path: /game-api
  port: 8082

#spring:
#  hateoas:
#    use-hal-as-default-json-media-type: false

palikka:
  jwt:
    keystore:
      signing:
        path: file:keystore-dev.p12
        pass: password
        type: pkcs12
      verification:
        path: file:truststore-dev.p12
        pass: password
        type: pkcs12
    token:
      user:
        issuer: palikka-dev-usr
        verification:
          key-alias: jwt-usr
      system:
        issuer: palikka-dev-sys
        signing:
          key-alias: jwt-sys
          key-pass: password
          validity-time: 10s
  integration:
    users-api:
      base-uri: http://palikka-users-api:8080
  game:
    file:
      name: server.jar
      path: /app # todo directory structure needs to exist currently, change?
      start-command: java -jar server.jar # todo omit name?
    status:
      host: localhost
    session:
      auto-clean:
        enabled: true
        fixed-delay: 60000

# todo delete these - debugging only
logging:
  level:
    fi.jannetahkola.palikka: debug
    org.springframework.web.socket: debug
    org.springframework.messaging: debug
    org.springframework.security: debug