server:
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path: /users-api
  port: 8080

spring:
  # setting this to false will produce correct Swagger for JSON with HATEOAS (no HAL)
  # users API uses HAL so here for reference
  # see https://github.com/springdoc/springdoc-openapi/issues/401
  hateoas:
    use-hal-as-default-json-media-type: true
  datasource:
    url: jdbc:postgresql://postgres:5432/palikka_users
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

springdoc:
  writer-with-order-by-keys: true

palikka:
  jwt:
    keystore:
      signing:
        path: file:keystore-dev.p12
        pass: password
        type: pkcs12
      verification:
        path: file:truststore-dev.p12
        pass: password
        type: pkcs12
    token:
      user:
        issuer: palikka-dev-usr
        signing:
          key-alias: jwt-usr
          key-pass: password
          validity-time: 1h
      system:
        issuer: palikka-dev-sys
        signing:
          key-alias: jwt-sys
          key-pass: password
          validity-time: 10s
  redis:
    host: redis
    port: 6379