insert into palikka_privilege (domain, name, domain_description)
values ('COMMAND', 'advancement', 'Gives, removes, or checks player advancements.'),
       ('COMMAND', 'attribute', 'Queries, adds, removes or sets an entity attribute.'),
       ('COMMAND', 'ban', 'Adds player to banlist.'),
       ('COMMAND', 'ban-ip', 'Adds IP address to banlist.'),
       ('COMMAND', 'banlist', 'Displays banlist.'),
       ('COMMAND', 'bossbar', 'Creates and modifies bossbars.'),
       ('COMMAND', 'clear', 'Clears items from player inventory.'),
       ('COMMAND', 'clone', 'Copies blocks from one place to another.'),
       ('COMMAND', 'damage', 'Applies damage to the specified entities.'),
       ('COMMAND', 'data', 'Gets, merges, modifies and removes block entity and entity NBT data.'),
       ('COMMAND', 'datapack', 'Controls loaded data packs.'),
       ('COMMAND', 'debug', 'Starts or stops a debugging session.'),
       ('COMMAND', 'defaultgamemode', 'Sets the default game mode.'),
       ('COMMAND', 'deop', 'Revokes operator status from a player.'),
       ('COMMAND', 'difficulty', 'Sets the difficulty level.'),
       ('COMMAND', 'effect', 'Adds or removes status effects.'),
       ('COMMAND', 'enchant', 'Adds an enchantment to a player''s selected item.'),
       ('COMMAND', 'execute', 'Executes another command.'),
       ('COMMAND', 'experience', 'An alias of /xp. Adds or removes player experience.'),
       ('COMMAND', 'fill', 'Fills a region with a specific block.'),
       ('COMMAND', 'fillbiome', 'Fills a region with a specific biome.'),
       ('COMMAND', 'forceload', 'Forces chunks to constantly be loaded or not.'),
       ('COMMAND', 'function', 'Runs a function.'),
       ('COMMAND', 'gamemode', 'Sets a player''s game mode.'),
       ('COMMAND', 'gamerule', 'Sets or queries a game rule value.'),
       ('COMMAND', 'give', 'Gives an item to a player.'),
       ('COMMAND', 'help', 'An alias of /?. Provides help for commands.'),
       ('COMMAND', 'item', 'Manipulates items in inventories.'),
       ('COMMAND', 'jfr', 'Starts or stops a JFR profiling.'),
       ('COMMAND', 'kick', 'Kicks a player off a server.'),
       ('COMMAND', 'kill', 'Kills entities (players, mobs, items, etc.).'),
       ('COMMAND', 'list', 'Lists players on the server.'),
       ('COMMAND', 'locate', 'Locates closest structure, biome, or point of interest.'),
       ('COMMAND', 'loot', 'Drops items from an inventory slot onto the ground.'),
       ('COMMAND', 'me', 'Displays a message about the sender.'),
       ('COMMAND', 'msg', 'An alias of /tell and /w. Displays a private message to other players.'),
       ('COMMAND', 'op', 'Grants operator status to a player.'),
       ('COMMAND', 'pardon', 'Removes entries from the banlist.'),
       ('COMMAND', 'pardon-ip', 'Removes entries from the banlist.'),
       ('COMMAND', 'particle', 'Creates particles.'),
       ('COMMAND', 'perf', 'Captures info and metrics about the game for 10 seconds.'),
       ('COMMAND', 'place', 'Used to place a configured feature, jigsaw, template, or structure at a given location.'),
       ('COMMAND', 'playsound', 'Plays a sound.'),
       ('COMMAND', 'publish', 'Opens single-player world to local network.'),
       ('COMMAND', 'random', 'Draw a random value or control the random number sequence.'),
       ('COMMAND', 'recipe', 'Gives or takes player recipes.'),
       ('COMMAND', 'reload', 'Reloads loot tables, advancements, and functions from disk.'),
       ('COMMAND', 'return', 'Control execution flow inside functions and change their return value.'),
       ('COMMAND', 'ride', 'Used to make entities ride other entities, stop entities from riding, make rides evict their riders, or summon rides or riders.'),
       ('COMMAND', 'save-all', 'Saves the server to disk.'),
       ('COMMAND', 'save-off', 'Disables automatic server saves.'),
       ('COMMAND', 'save-on', 'Enables automatic server saves.'),
       ('COMMAND', 'say', 'Displays a message to multiple players.'),
       ('COMMAND', 'schedule', 'Delays the execution of a function.'),
       ('COMMAND', 'scoreboard', 'Manages scoreboard objectives and players.'),
       ('COMMAND', 'seed', 'Displays the world seed.'),
       ('COMMAND', 'setblock', 'Changes a block to another block.'),
       ('COMMAND', 'setidletimeout', 'Sets the time before idle players are kicked.'),
       ('COMMAND', 'setworldspawn', 'Sets the world spawn.'),
       ('COMMAND', 'spawnpoint', 'Sets the spawn point for a player.'),
       ('COMMAND', 'spectate', 'Make one player in spectator mode spectate an entity.'),
       ('COMMAND', 'spreadplayers', 'Teleports entities to random locations.'),
       ('COMMAND', 'stop', 'Stops a server.'),
       ('COMMAND', 'stopsound', 'Stops a sound.'),
       ('COMMAND', 'summon', 'Summons an entity.'),
       ('COMMAND', 'tag', 'Controls entity tags.'),
       ('COMMAND', 'team', 'Controls teams.'),
       ('COMMAND', 'teammsg', 'An alias of /tm. Specifies the message to send to team.'),
       ('COMMAND', 'teleport', 'An alias of /tp. Teleports entities.'),
       ('COMMAND', 'tell', 'An alias of /msg and /w. Displays a private message to other players.'),
       ('COMMAND', 'tellraw', 'Displays a JSON message to players.'),
       ('COMMAND', 'time', 'Changes or queries the world''s game time.'),
       ('COMMAND', 'title', 'Manages screen titles.'),
       ('COMMAND', 'tm', 'An alias of /teammsg. Specifies the message to send to team.'),
       ('COMMAND', 'tp', 'An alias of /teleport. Teleports entities.'),
       ('COMMAND', 'trigger', 'Sets a trigger to be activated.'),
       ('COMMAND', 'w', 'An alias of /tell and /msg. Displays a private message to other players.'),
       ('COMMAND', 'weather', 'Sets the weather.'),
       ('COMMAND', 'whitelist', 'Manages server whitelist.'),
       ('COMMAND', 'worldborder', 'Manages the world border.'),
       ('COMMAND', 'xp', 'An alias of /experience. Adds or removes player experience.')
;