version: '3.8'
services:
  palikka-game-api:
    container_name: palikka-game-api
    build:
      context: ./palikka-game-api
      dockerfile: Dockerfile
    ports:
      - '8082:8082'
    volumes:
      # todo add jwks endpoint to users rather than sharing the key stores
      - ./conf/keystore-dev.p12:/app/keystore-dev.p12
      - ./conf/truststore-dev.p12:/app/truststore-dev.p12

  palikka-mock-file-server:
    container_name: palikka-mock-file-server
    build:
      context: ./palikka-mock-file-server
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    volumes:
      - ./conf/public/server.jar:/app/public/server.jar