services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:9.9-community
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
      - SONAR_JDBC_USERNAME=user
      - SONAR_JDBC_PASSWORD=password
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - 9000:9000

  postgres:
    container_name: postgres
    image: postgres:16.2
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=palikka_users
    volumes:
      - postgres:/var/lib/postgresql
      - postgres_data:/var/lib/postgresql/data
      # anything inside this folder will be executed on start up
      - ./conf/data/sonar:/docker-entrypoint-initdb.d

  redis:
    container_name: redis
    image: redis:7.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis:/redis/data

  palikka-users-api:
    container_name: palikka-users-api
    build:
      context: ./palikka-users-api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./conf/keystore-dev.p12:/app/keystore-dev.p12
      - ./conf/truststore-dev.p12:/app/truststore-dev.p12
#    networks:
#      - palikkanet

  palikka-game-api:
    container_name: palikka-game-api
    build:
      context: ./palikka-game-api
      dockerfile: Dockerfile
    ports:
      - 8082:8082
      - 25565:25565
    volumes:
      - ./conf/keystore-dev.p12:/app/keystore-dev.p12
      - ./conf/truststore-dev.p12:/app/truststore-dev.p12
      - game:/app/game
#    networks:
#      - palikkanet

  palikka-mock-file-server:
    container_name: palikka-mock-file-server
    build:
      context: ./palikka-mock-file-server
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    volumes:
      - ./conf/public/server.jar:/app/public/server.jar
#    networks:
#      - palikkanet
#
#networks:
#  palikkanet:
#    name: palikkanet
#    external: true

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgres:
  postgres_data:
  redis:
    driver: local
  game:
    driver: local