services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:9.9-community
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
      - SONAR_JDBC_USERNAME=user
      - SONAR_JDBC_PASSWORD=password
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - 9000:9000
    networks:
      - palikka-api-net

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:

networks:
  palikka-api-net:
    name: palikka-api-net
    external: true