version: '3.8'
services:
  palikka_game_api:
    container_name: palikka_game_api
    build:
      context: ./palikka-game-api
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./conf/dev.keystore:/app/palikka.keystore

  palikka_mock_file_server:
    container_name: palikka_mock_file_server
    build:
      context: ./palikka-mock-file-server
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    volumes:
      - ./conf/public/server.jar:/app/public/server.jar