services:
  redis:
    container_name: redis
    image: redis:7.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis:/redis/data
    networks:
      - palikka-api-net

  palikka-users-api:
    container_name: palikka-users-api
    build:
      context: .
      dockerfile: palikka-users-api.Dockerfile
      # build stage will access SonarQube container through host
      network: host
    volumes:
      - ./conf/keystore-dev.p12:/app/keystore-dev.p12
      - ./conf/truststore-dev.p12:/app/truststore-dev.p12
    ports:
      - 8080:8080
    networks:
      - palikka-api-net
    depends_on:
      - redis

  palikka-game-api:
    container_name: palikka-game-api
    build:
      context: .
      dockerfile: palikka-game-api.Dockerfile
      # build stage will access SonarQube container through host
      network: host
    volumes:
      - ./conf/keystore-dev.p12:/app/keystore-dev.p12
      - ./conf/truststore-dev.p12:/app/truststore-dev.p12
      - game:/app/game
    ports:
      - 8082:8082
      - 25565:25565
    networks:
      - palikka-api-net

  palikka-mock-file-server:
    container_name: palikka-mock-file-server
    build:
      context: .
      dockerfile: palikka-mock-file-server.Dockerfile
    volumes:
      - ./conf/public/server.jar:/app/public/server.jar
    ports:
      - 8081:8081
    networks:
      - palikka-api-net

volumes:
  redis:
    driver: local
  game:
    driver: local

networks:
  palikka-api-net:
    name: palikka-api-net
    external: true